Feature/password management
moka-guys/guidance pull request #12
Opened 2023-02-09 17:02 UTC by RachelDuffin

- Split secrets guidance into own document and add to password and access guidance
- Set up GitHub Pages deployment

2023-02-27 17:52 UTC, aledj2 requested changes
> Reviewed 9 of 34 files at r1, 24 of 27 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/guidance/12)* status: 35 of 36 files reviewed, 2 unresolved discussions (waiting on @preciserobot and @RachelDuffin)

___
*[`docs/01_seglh-overview.md` line 19 at r3](https://reviewable.io/reviews/moka-guys/guidance/12#-NPIvPZNBlD5Uiuv3XcN:-NPIvPZNBlD5Uiuv3XcO:b-8ir2f2) ([raw file](https://github.com/moka-guys/guidance/blob/53d9d68d6a770fe36c1142ab906a2323a1c05f36/docs/01_seglh-overview.md#L19)):*
> ```Markdown
> tooling to enhance interoperability and sets out a framework to allow collaborative development of software.
> 
> These guidance documents cover coding style, versioning, and do
> ```

is this split over 2 lines or just displayed funny in reviewable?
___
*[`docs/07_seglh-secrets.md` line 16 at r3](https://reviewable.io/reviews/moka-guys/guidance/12#-NPIwJKPBgdTI4MePniV:-NPIwJKPBgdTI4MePniW:b-u7i07g) ([raw file](https://github.com/moka-guys/guidance/blob/53d9d68d6a770fe36c1142ab906a2323a1c05f36/docs/07_seglh-secrets.md#L16)):*
> ```Markdown
> ## root accounts
> 
> All compute assets running Linux, must have a root account protected by the KingPM master password as well as the
> ```

remove KingPM?



_Code quote:_
```Markdown
KingPM
```


<!-- Sent from Reviewable.io -->

2023-02-28 08:59 UTC, RachelDuffin reviewed
> *[Reviewable](https://reviewable.io/reviews/moka-guys/guidance/12)* status: 34 of 36 files reviewed, 2 unresolved discussions (waiting on @aledj2 and @preciserobot)

___
*[`docs/01_seglh-overview.md` line 19 at r3](https://reviewable.io/reviews/moka-guys/guidance/12#-NPIvPZNBlD5Uiuv3XcN:-NPMEs1MBWDSXTLk9XX-:b45b2mf) ([raw file](https://github.com/moka-guys/guidance/blob/53d9d68d6a770fe36c1142ab906a2323a1c05f36/docs/01_seglh-overview.md#L19)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

is this split over 2 lines or just displayed funny in reviewable?
</blockquote></details>

Good spot, I've now removed this
___
*[`docs/07_seglh-secrets.md` line 16 at r3](https://reviewable.io/reviews/moka-guys/guidance/12#-NPIwJKPBgdTI4MePniV:-NPME0eKAKEUFRillydV:b-34n83f) ([raw file](https://github.com/moka-guys/guidance/blob/53d9d68d6a770fe36c1142ab906a2323a1c05f36/docs/07_seglh-secrets.md#L16)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

remove KingPM?
</blockquote></details>

I'm not sure what this is and it's in the master branch so wasn't added by me - I think I'll need to check with David!


<!-- Sent from Reviewable.io -->

2023-02-28 09:14 UTC, RachelDuffin reviewed
> *[Reviewable](https://reviewable.io/reviews/moka-guys/guidance/12)* status: 34 of 36 files reviewed, 2 unresolved discussions (waiting on @aledj2 and @preciserobot)

___
*[`docs/07_seglh-secrets.md` line 16 at r3](https://reviewable.io/reviews/moka-guys/guidance/12#-NPIwJKPBgdTI4MePniV:-NPMIEGp0HSPpKCOdeZU:b-vzw1a0) ([raw file](https://github.com/moka-guys/guidance/blob/53d9d68d6a770fe36c1142ab906a2323a1c05f36/docs/07_seglh-secrets.md#L16)):*
<details><summary><i>Previously, RachelDuffin wrote…</i></summary><blockquote>

I'm not sure what this is and it's in the master branch so wasn't added by me - I think I'll need to check with David!
</blockquote></details>

I've now updated this to something multi-team applicable


<!-- Sent from Reviewable.io -->

2023-02-28 09:16 UTC, aledj2 approved these changes
> Reviewed 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/guidance/12)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @preciserobot)



<!-- Sent from Reviewable.io -->

2023-03-08 09:42 UTC, merged